pipeline:
  build:
    image: docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - docker build -t vlt/helloworld:v${DRONE_BUILD_NUMBER} .
  rancher:
    image: peloton/drone-rancher
    service: test/test
    docker_image: vlt/helloworld:v${DRONE_BUILD_NUMBER}
    confirm: true
    timeout: 300
    secrets: [ plugin_url, rancher_access_key, rancher_secret_key ]
